package cjb.compiler;
import cjb.util.UiUtil;
import java.awt.Color;
import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileWriter;
import java.util.Set;

/**
 *
 * @author Lenovo
 */
public class LexerFrame extends javax.swing.JFrame {

    /**
     * Creates new form LexerFrame
     */
    public LexerFrame() {
        initComponents();
        UiUtil.setFrameImage(this);
        UiUtil.setFrameCenter(this);
        this.setAutoRequestFocus(true);
        this.tokens.setVisible(false);
        this.symbols.setVisible(false);
        this.errors.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        editText = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tokens = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        symbols = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        errors = new javax.swing.JTextArea();
        label2 = new java.awt.Label();
        label1 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        textArea1 = new java.awt.TextArea();
        label5 = new java.awt.Label();
        file = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        newSet = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        cancel = new javax.swing.JMenuItem();
        cut = new javax.swing.JMenuItem();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        delete = new javax.swing.JMenuItem();
        test = new javax.swing.JMenu();
        lexerError = new javax.swing.JMenuItem();
        run = new javax.swing.JMenu();
        testLexer = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("词法分析器");
        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(0, 255, 204));

        jScrollPane1.setBackground(new java.awt.Color(0, 153, 204));
        jScrollPane1.setForeground(new java.awt.Color(0, 204, 204));

        editText.setBackground(new java.awt.Color(102, 102, 102));
        editText.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(editText);

        tokens.setBackground(new java.awt.Color(0, 153, 153));
        tokens.setColumns(20);
        tokens.setRows(5);
        jScrollPane2.setViewportView(tokens);

        symbols.setBackground(new java.awt.Color(153, 51, 255));
        symbols.setColumns(20);
        symbols.setRows(5);
        jScrollPane3.setViewportView(symbols);

        jScrollPane8.setBackground(new java.awt.Color(0, 204, 204));

        errors.setBackground(new java.awt.Color(255, 51, 51));
        errors.setColumns(20);
        errors.setRows(5);
        jScrollPane8.setViewportView(errors);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setForeground(new java.awt.Color(0, 0, 204));
        label2.setText("符号表");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setForeground(new java.awt.Color(0, 0, 204));
        label1.setText("词法错误表");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setForeground(new java.awt.Color(0, 0, 204));
        label3.setText("代码编辑区域");

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setForeground(new java.awt.Color(0, 0, 204));
        label4.setText("token表");

        textArea1.setBackground(new java.awt.Color(255, 204, 204));
        textArea1.setForeground(new java.awt.Color(0, 0, 204));

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setForeground(new java.awt.Color(0, 0, 204));
        label5.setText("语法分析");

        file.setBackground(new java.awt.Color(0, 204, 204));
        file.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("文件");

        open.setText("打开");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jMenu1.add(open);

        newSet.setText("新建文件");
        newSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSetActionPerformed(evt);
            }
        });
        jMenu1.add(newSet);

        file.add(jMenu1);

        edit.setText("编辑");

        cancel.setText("撤销");
        edit.add(cancel);

        cut.setText("剪切");
        edit.add(cut);

        copy.setText("复制");
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        edit.add(copy);

        paste.setText("粘贴");
        edit.add(paste);

        delete.setText("清除");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        edit.add(delete);

        file.add(edit);

        test.setText("调试");

        lexerError.setText("词法错误");
        lexerError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexerErrorActionPerformed(evt);
            }
        });
        test.add(lexerError);

        file.add(test);

        run.setText("运行");

        testLexer.setText("测试词法");
        testLexer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLexerActionPerformed(evt);
            }
        });
        run.add(testLexer);

        jMenuItem1.setText("测试语法");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        run.add(jMenuItem1);

        file.add(run);

        setJMenuBar(file);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(215, 215, 215)
                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2)))
        );

        label4.getAccessibleContext().setAccessibleName("label11");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyActionPerformed

    private void lexerErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexerErrorActionPerformed
        this.errors.setBackground(Color.red);
    }//GEN-LAST:event_lexerErrorActionPerformed

   private void writeTosrc() throws IOException{
       BufferedWriter br=new BufferedWriter(new FileWriter("src\\yuan.txt"));
       String s=this.editText.getText();
       br.write(s);
       br.flush();
       br.close();
       
   }    
    private void testLexerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testLexerActionPerformed
       
              this.editText.setBackground(Color.green);
              this.editText.setForeground(Color.blue);
                try{
                     writeTosrc();
                }catch(IOException e){
                    System.out.println(e);
                }
                Lexer lexer=new Lexer("src\\yuan.txt","src\\symbol.txt","src\\token.txt","src\\error.txt");
                while(lexer.getReaderState()==false) {
                                try {
                                        lexer.anlalyse();
                                } catch (IOException e) {
                                        System.out.println(e);
                                }
                }
                try {
                      String errorString=  lexer.savaError();
                      String symbolString=lexer.savaSymbols();
                      String tokenString=lexer.saveTokens();
                      this.tokens.setText(tokenString);
                      this.errors.setText(errorString);
                      this.symbols.setText(symbolString);
                      this.tokens.setVisible(true);
                      this.errors.setVisible(true);
                      this.symbols.setVisible(true);
                } catch (IOException e) {
                        System.out.println(e);
                }
                
                
    }//GEN-LAST:event_testLexerActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        this.editText.setText("");
        this.tokens.setText("");
        this.errors.setText("");
        this.symbols.setText("");
        this.errors.setVisible(false);
        this.tokens.setVisible(false);
        this.symbols.setVisible(false);
    }//GEN-LAST:event_deleteActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        FileDialog fd=new FileDialog(this);
        fd.setVisible(true);
        String s=fd.getDirectory();
        String ss=fd.getFile();
        String path=s+ss;
        File file=new File(path);
        try{
            BufferedReader br=new BufferedReader(new FileReader(file));
            StringBuffer sb=new StringBuffer();
            String line=null;
            while((line=br.readLine())!=null){
                   sb.append(line);
                   sb.append("\n");
            }
            this.editText.setText(sb.toString());
        }catch(IOException e){
            System.out.println(e);
        }
        
                
    }//GEN-LAST:event_openActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       try {
			SyntacticAnalyzer sa=new SyntacticAnalyzer();
			sa.program();
                       
			if(sa.errorsMap.isEmpty()){
                            sa.sb.append("语法正确！\n");
//				System.out.println("璇硶姝ｇ‘");
			}else{
//				Set set=sa.errorsMap.keySet();
//				for (Object obj : set) {
//					String key=(String)obj;
//					System.out.println(key+sa.errorsMap.get(key));
//				}
                            sa.sb.append("语法错误！\n");
			}
                         textArea1.setText(sa.sb.toString());
		} catch (IOException e) {
			System.out.println(e);
		}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void newSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSetActionPerformed
        
    }//GEN-LAST:event_newSetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LexerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LexerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LexerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LexerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LexerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cancel;
    private javax.swing.JMenuItem copy;
    private javax.swing.JMenuItem cut;
    private javax.swing.JMenuItem delete;
    private javax.swing.JMenu edit;
    private javax.swing.JEditorPane editText;
    private javax.swing.JTextArea errors;
    private javax.swing.JMenuBar file;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane8;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JMenuItem lexerError;
    private javax.swing.JMenuItem newSet;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem paste;
    private javax.swing.JMenu run;
    private javax.swing.JTextArea symbols;
    private javax.swing.JMenu test;
    private javax.swing.JMenuItem testLexer;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextArea tokens;
    // End of variables declaration//GEN-END:variables
}
