package cjb.compiler;

public class Word {
	public static final String and ="&&",
			or="||",
//			doubleEqual="==",
			equal="=",
			notEqual="!=",
			lessEqual="<=",
			less="<",
//			greaterEqual=">=",
			greater=">",
			plus="+",
			plusPlus="++",
			plusEqual="+=",
			minus="-",
			minusMinus="--",
			minusEqual="-=",
			True="true",
			False="false",
			Int="int",
			Double="double",
			Float = "float",  
	        Char = "char",   
	        Boolean = "boolean",  
	        String = "String",  
	        Private = "private",  
	        Public = "public",  
	        Protected = "protected",
			leftBracket="(",
			rightBracket=")",
			LBracket="[",
			RBracket="]",
			BLBracket="{",
			BRBracket="}",
			comma=",",
			doubleMark="\"",
			singleMark="\'",
			semicolon=";",
			dot=".";

}
